clear;clc;
I = imread('2.png');
BW = im2bw(I,0.4);
IBW = ~BW;
F1 = imfill(IBW,'holes');
SE = ones(3);
F2 = imdilate(F1,SE,'same');
BW3 = bwperim(F2);
subplot(1,2,1);
imshow(I);
title('original iamge');
subplot(1,2,2), imshow(BW3);
title('operated bwperim'); 
